name = "KhepriRhino"
uuid = "27da4253-bb12-40dc-baea-7a8a96820661"
authors = ["António Menezes Leitão <antonio.menezes.leitao@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
